version: '3.8'

services:
  flight-agent:
    build: .
    container_name: flight-agent
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8501:8501"  # Streamlit port
    networks:
      - app-network

  webhook:
    image: almir/webhook
    container_name: webhook
    restart: unless-stopped
    command: ["-hooks", "/etc/webhook/hooks.yaml", "-verbose"]
    volumes:
      - /home/deployer/steward/webhook:/etc/webhook
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/deployer/steward/docker-compose.yml:/etc/webhook/docker-compose.yml
    ports:
      - "9000:9000"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - HOOKS_FILE=/etc/webhook/hooks.yaml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 